# Generated by Django 3.1.7 on 2022-02-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='last name'),
        ),
    ]
