# Generated by Django 3.1.7 on 2022-02-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220226_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dateCreation',
            field=models.DateField(auto_now=True, verbose_name='date'),
        ),
    ]
