# Generated by Django 3.1.7 on 2022-02-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_datecreation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dateCreation',
        ),
        migrations.AddField(
            model_name='task',
            name='dateTimeCreation',
            field=models.DateTimeField(auto_now=True, verbose_name='date'),
        ),
    ]
