# Generated by Django 3.1.7 on 2022-02-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20220227_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['dateTimeCreation']},
        ),
    ]
