# Generated by Django 3.1.7 on 2022-02-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20220228_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-dateTimeCreation']},
        ),
    ]
